######################## default configuration ####################
baseURL = "/"
title = "ClyDe - Group 9"
theme = "bigspring"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################
[permalinks]
pages = "/:slug"

# main menu
[[menu.main]]
name = "System"
URL = "system"
weight = 1

[[menu.main]]
name = "How it works"
URL = "how-it-works"
weight = 2

[[menu.main]]
name = "Evaluation"
URL = "evaluation"
weight = 3

[[menu.main]]
name = "Budget"
URL = "budget"
weight = 4

[[menu.main]]
name = "Team"
URL = "team"
weight = 5

# company 
[[menu.more]]
name = "Link"
URL = "#"

[[menu.more]]
name = "Link"
URL = "#"

[[menu.more]]
name = "Link"
URL = "#"

# Product 
[[menu.reports]]
name = "Link"
URL = "#"

[[menu.reports]]
name = "Link"
URL = "#"

[[menu.reports]]
name = "Link"
URL = "#"

# Support 
[[menu.videos]]
name = "Link"
URL = "#"

[[menu.videos]]
name = "Link"
URL = "#"

[[menu.videos]]
name = "Link"
URL = "#"

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "200px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

########### footer content ##########
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = false
label = "Get Started"
link = "contact"
